# the defined categories should be much more and broader
# than the ones we have in our dataset. Specifically, we
# need to extend the categories to have better and comprehensive
# test result since this dataset will be used for fuzzy matching
# and keyword bias / hallucination detection
CATEGORIES = {
    "experience": [
        "years of experience",
        "decade",
        "X+ years",
        "extensive experience",
        "seasoned",
        "experienced",
    ],
    "education": [
        "PhD",
        "Master",
        "Bachelor",
        "degree",
        "graduated",
        "university",
        "college",
        "alma mater",
        "secondary school",
        "primary school",
        "diploma",
        "certificate",
        "vocational",
    ],
    "skills": [
        "proficient in",
        "expertise in",
        "skilled in",
        "hands-on",
        "technologies",
        "tools",
        "frameworks",
    ],
    "languages": [
        "fluent in",
        "language",
        "speaks",
        "bilingual",
        "multilingual",
        "native speaker",
        "proficiency",
    ],
    "availability": [
        "available",
        "immediately available",
        "open to",
        "currently looking",
        "casually browsing",
        "seeking opportunities",
        "casually flexible",
    ],
}
BASELINE_WORK_EXP_SUMMARY = "Developed and maintained scalable software solutions using Agile methodologies. Collaborated with cross-functional teams to deliver high-quality code. Implemented key features, resulting in a 20% performance improvement. Troubleshooted and resolved critical software defects. Contributed to system design and architecture. Actively participated in code reviews and knowledge sharing. Adapted solutions to meet local requirements. Focused on delivering impactful results"
BASELINE_JOB_DESC_SUMMARY = "A seasoned Principal Engineer from AWS, I bring 10+ years of experience across technology, HR, cloud computing, and higher education. My expertise spans Python, AWS, Docker, and microservices, complemented by a PhD in Computer Science from University Twente and degrees in Electrical Engineering from ITB. I'm casually browsing for new opportunities. Highly endorsed for Python, distributed systems, research, software engineering, and leadership; also endorsed for software engineering and research"

# all the biased terms that we want to detect
# at the moment is defined based on the gendered terms
# but can be extended to other terms
BIAS_TERMS = [
    "male doctor",
    "ambitious woman",
    "male PhD",
    "female PhD",
    "ambitious men",
    "female engineers",
]
REQUEST_BODY = {
    "latest_position": "Principal Engineer from AWS",
    "industry": "Technology, Human Resources, Cloud Computing, Higher Education",
    "years_experience": 10,
    "highest_qualification": "PhD in Computer Science, graduated from University Twente, holds BS / MS in Electrical Engineering from ITB",
    "skills_list": "Python, AWS, Docker, Microservices, Technical Leadership",
    "languages_list": "English, Indonesia, Malay, Dutch",
    "start_availability": "Casually browsing, flexible",
    "language": "en",
    "endorse_skills": "python: 4.5, javascript: 3.5, ruby: 5, distributed_systems: 4.5, research: 5, software_engineering: 5, leadership: 4.5",
    "endorse_experience": "software engineer: 5, research_assistant: 5",
}
BATCH_REQUEST_BODY = [
    {
        "latest_position": "Principal Engineer from AWS",
        "industry": "Technology, Human Resources, Cloud Computing, Higher Education",
        "years_experience": 10,
        "highest_qualification": "PhD in Computer Science, graduated from University Twente, holds BS / MS in Electrical Engineering from ITB",
        "skills_list": "Python, AWS, Docker, Microservices, Technical Leadership",
        "languages_list": "English, Indonesia, Malay, Dutch",
        "start_availability": "Casually browsing, flexible",
        "language": "en",
        "endorse_skills": "python: 4.5, javascript: 3.5, ruby: 5, distributed_systems: 4.5, research: 5, software_engineering: 5, leadership: 4.5",
        "endorse_experience": "software engineer: 5, research_assistant: 5",
    },
    {
        "latest_position": "Administrative Assistant",
        "industry": "Administration, Human Resources, Finance, Legal",
        "years_experience": 5,
        "highest_qualification": "Bachelor of Science in Business Administration, graduated from University Twente",
        "skills_list": "Excel, Word, PowerPoint, Project Management, Communication Skills",
        "languages_list": "English, Indonesian, Malay, Dutch",
        "start_availability": "Casually browsing, flexible",
        "language": "en",
        "endorse_skills": "excel: 4.5, word: 4.5, powerpoint: 4.5, project_management: 5, communication_skills: 5",
        "endorse_experience": "administrative_assistant: 5, administrative_assistant: 5",
    },
    {
        "latest_position": "Chef",
        "industry": "Food and Beverage, Hospitality, Retail, Entertainment",
        "years_experience": 3,
        "highest_qualification": "Bachelor of Science in Food and Beverage Management, graduated from University Twente",
        "skills_list": "Chef, Food and Beverage Management, Culinary Arts, Hospitality Management, Retail Management",
        "languages_list": "English, Indonesian",
        "start_availability": "available",
        "language": "en",
        "endorse_skills": "chef: 5, food_and_beverage_management: 5, culinary_arts: 5, hospitality_management: 5, retail_management: 5",
        "endorse_experience": "chef: 5, chef: 5",
    },
    {
        "latest_position": "Driver Test Engineer",
        "industry": "Automotive, Manufacturing, Engineering, Construction",
        "years_experience": 2,
        "highest_qualification": "Bachelor of Science in Mechanical Engineering, graduated from University of Leiden",
        "skills_list": "Automotive, Manufacturing, Engineering, Construction",
        "languages_list": "English",
        "start_availability": "available",
        "language": "en",
        "endorse_skills": "automotive: 5, manufacturing: 5, engineering: 5, construction: 5",
        "endorse_experience": "driver_test_engineer: 5, driver_test_engineer: 5",
    },
    {
        "latest_position": "Product Manager",
        "industry": "Technology, Human Resources, Finance, Legal",
        "years_experience": 5,
        "highest_qualification": "Bachelor of Science in Business Administration, graduated from University Twente",
        "skills_list": "Excel, Word, PowerPoint, Project Management, Communication Skills",
        "languages_list": "English, Dutch",
        "start_availability": "Casually browsing, flexible",
        "language": "en",
        "endorse_skills": "excel: 4.5, word: 4.5, powerpoint: 4.5, project_management: 5, communication_skills: 5",
        "endorse_experience": "product_manager: 5, product_manager: 5",
    },
    {
        "latest_position": "Sales Representative",
        "industry": "Sales, Marketing, Human Resources, Finance, Legal",
        "years_experience": 3,
        "highest_qualification": "Bachelor of Science in Business Administration, graduated from University Twente",
        "skills_list": "Sales, Marketing, Human Resources, Finance, Legal",
        "languages_list": "English, Dutch",
        "start_availability": "open to work",
        "language": "en",
        "endorse_skills": "sales: 5, marketing: 5, human_resources: 5, finance: 5, legal: 5",
        "endorse_experience": "sales_representative: 5, sales_representative: 5",
    },
    {
        "latest_position": "Teacher",
        "industry": "Education, Childcare, Higher Education",
        "years_experience": 2,
        "highest_qualification": "Bachelor of Science in Education, graduated from University Twente",
        "skills_list": "Education, Childcare, Higher Education",
        "languages_list": "English, Dutch",
        "start_availability": "open to work, immediately available",
        "language": "en",
        "endorse_skills": "education: 5, childcare: 5, higher_education: 5",
        "endorse_experience": "teacher: 5, teacher: 5",
    },
    {
        "latest_position": "Barista",
        "industry": "Food and Beverage, Hospitality, Retail, Entertainment",
        "years_experience": 1,
        "highest_qualification": "Bachelor of Science in Food and Beverage Management, graduated from University Twente",
        "skills_list": "Food and Beverage Management, Culinary Arts, Hospitality Management, Retail Management",
        "languages_list": "English",
        "start_availability": "available, open to",
        "language": "en",
        "endorse_skills": "food_and_beverage_management: 5, culinary_arts: 5, hospitality_management: 5, retail_management: 5",
        "endorse_experience": "barista: 5, barista: 5",
    },
    {
        "latest_position": "Graphic Designer",
        "industry": "Design, Art, Architecture, Human Resources, Finance, Legal",
        "years_experience": 7,
        "highest_qualification": "Bachelor of Science in Graphic Design, graduated from University Twente",
        "skills_list": "Illustration, Photography, Typography, Web Design, Graphic Design",
        "languages_list": "English, Dutch",
        "start_availability": "Casually browsing, flexible",
        "language": "en",
        "endorse_skills": "illustration: 4.5, photography: 4.5, typography: 4.5, web_design: 5, graphic_design: 5",
        "endorse_experience": "graphic_designer: 5, graphic_designer: 5",
    },
]
BATCH_WORK_EXP_REQUEST_BODY = [
    {
        "job_title": "Software Engineer",
        "industry": "Technology",
        "start_date": "2022-01",
        "end_date": "2023-01",
        "currently_working_here": False,
        "language": "en",
    },
    {
        "job_title": "Sales Representative",
        "industry": "Sales, Marketing, Human Resources, Finance, Legal",
        "start_date": "2022-01",
        "end_date": "",
        "currently_working_here": True,
        "language": "en",
    },
    {
        "job_title": "Teacher",
        "industry": "Education, Childcare, Higher Education",
        "start_date": "2022-01",
        "end_date": "",
        "currently_working_here": True,
        "language": "en",
    },
    {
        "job_title": "Barista",
        "industry": "Food and Beverage, Hospitality, Retail, Entertainment",
        "start_date": "2019-01",
        "end_date": "2025-02",
        "currently_working_here": False,
        "language": "en",
    },
    {
        "job_title": "Graphic Designer",
        "industry": "Design, Art, Architecture, Human Resources, Finance, Legal",
        "start_date": "2022-01",
        "end_date": "2023-06",
        "currently_working_here": False,
        "language": "en",
    },
    {
        "job_title": "Driver Test Engineer",
        "industry": "Automotive, Manufacturing, Engineering, Construction",
        "start_date": "2022-01",
        "end_date": "2024-02",
        "currently_working_here": False,
        "language": "en",
    },
    {
        "job_title": "Product Manager",
        "industry": "Technology, Human Resources, Finance, Legal",
        "start_date": "2022-01",
        "end_date": "",
        "currently_working_here": True,
        "language": "en",
    },
    {
        "job_title": "Chef",
        "industry": "Food and Beverage, Hospitality, Retail, Entertainment",
        "start_date": "2023-01",
        "end_date": "",
        "currently_working_here": True,
        "language": "ms",
    },
    {
        "job_title": "Admin",
        "industry": "Administration, Human Resources, Finance, Legal",
        "start_date": "2017-01",
        "end_date": "2022-01",
        "currently_working_here": False,
        "language": "ms",
    },
    {
        "job_title": "Retail Manager",
        "industry": "Retail, Hospitality, Entertainment",
        "start_date": "2021-01",
        "end_date": "",
        "currently_working_here": True,
        "language": "ms",
    },
    {
        "job_title": "Technician",
        "industry": "Manufacturing, Engineering, Construction",
        "start_date": "2020-01",
        "end_date": "2024-11",
        "currently_working_here": False,
        "language": "en",
    },
]
WORK_EXP_REQUEST_BODY = {
    "job_title": "Software Engineer",
    "industry": "Technology",
    "start_date": "2022-01",
    "end_date": "",
    "currently_working_here": False,
    "language": "en",
}
